name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag karisgwet/tp4_test:tagname | docker tag <bab44c8661b9> <karisgwet>/<flask-app-3>:<tag> | docker push karisgwet/tp4_test:tagname
