name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    context: .
      dockerfile: ./backend/dockerfile
      run: docker build -t karisgwet/tp4_test:flask-app-3 . | docker push karisgwet/tp4_test:flask-app-3