name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    context: .
      run: | 
        echo "${{ secrets.dockerhub176 }}" | docker login -u "${{ secrets.karisgwet }}" --password-stdin docker.io
        docker build . --file Dockerfile --tag docker.io/${{ secrets.karisgwet }}/${{ secrets.tp4_test }}:flask-app-3
        docker push docker.io/${{ secrets.karisgwet }}/${{ secrets.tp4_test }}:flask-app-3