name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    context: .
      dockerfile: ./backend/dockerfile
      run: docker login -u ykarisgwet -p pauline176| docker build -t karisgwet/tp4_test:latest . | docker push karisgwet/tp4_test:latest